//
// Created by 周洋 on 2020/4/1.
//

#ifndef RECORDERCONFIGER_CONFIGUTIL_H
#define RECORDERCONFIGER_CONFIGUTIL_H

#include "public.h"
#define TAG_MODELTYPE   "ModelType"
#define TAG_ENABLE      "Enable"
#define TAG_BASE        "Base"
    #define TAG_POSCFG      "Pos_Config"
        #define TAG_FIXED   "Pos_Fixed"
            #define TAG_ECEF    "Pos_Elef"
                #define TAG_ECEF_X          "Ecef_X"
                #define TAG_ECEF_X_HP       "Ecef_X_HP"
                #define TAG_ECEF_Y          "Ecef_Y"
                #define TAG_ECEF_Y_HP       "Ecef_Y_HP"
                #define TAG_ECEF_Z          "Ecef_Z"
                #define TAG_ECEF_Z_HP       "Ecef_Z_HP"
            #define TAG_LLA         "Pos_Lla"
                #define TAG_LLA_LAT         "Lla_Lat"
                #define TAG_LLA_LAT_HP      "Lla_lat_HP"
                #define TAG_LLA_LON         "Lla_lon"
                #define TAG_LLA_LON_HP      "Lla_lon_HP"
                #define TAG_LLA_ALT         "Lla_alt"
                #define TAG_LLA_ALT_HP      "Lla_alt_HP"
            #define TAG_FIXED_ACC   "Fixed_Acc"

        #define TAG_SURVEYIN    "Pos_Surveyin"
            #define TAG_DURL            "Durl"
            #define TAG_SVIN_ACC           "Svin_Acc"
    #define TAG_ROVER       "Rover"
        #define TAG_OUTRATE     "Out_Rate"
#define TAG_UART		"Uart"
	#define TAG_MCUCFGPORT			"McuCfgPort"
	#define TAG_UBXPORT1			"UbxPort1"
	#define TAG_UBXPORT2    		"UbxPort2"

#define TAG_MSGOUT  "MsgOut"
    #define TAG_MSGNMEA "NMEA"
        #define TAG_NMEA_DTM    "GxDTM"
        #define TAG_NMEA_GBS    "GxGBS"
        #define TAG_NMEA_GGA    "GxGGA"
        #define TAG_NMEA_GLL    "GxGLL"
        #define TAG_NMEA_GNS    "GxGNS"
        #define TAG_NMEA_GRS    "GxGRS"
        #define TAG_NMEA_GSA    "GxGSA"
        #define TAG_NMEA_GST    "GxGST"
        #define TAG_NMEA_GSV    "GxGSV"
        #define TAG_NMEA_RMC    "GxRMC"
        #define TAG_NMEA_VLW    "GxVLW"
        #define TAG_NMEA_ZTG    "GxZTG"
        #define TAG_NMEA_ZDA    "GxZDA"
    #define TAG_MSGRTCM "RTCM"
        #define TAG_RTCM_1005           "RTCM_1005"
        #define TAG_RTCM_1074           "RTCM_1074"
        #define TAG_RTCM_1077           "RTCM_1077"
        #define TAG_RTCM_1084           "RTCM_1084"
        #define TAG_RTCM_1087           "RTCM_1087"
        #define TAG_RTCM_1094           "RTCM_1094"
        #define TAG_RTCM_1097           "RTCM_1097"
        #define TAG_RTCM_1124           "RTCM_1124"
        #define TAG_RTCM_1127           "RTCM_1127"
        #define TAG_RTCM_1230           "RTCM_1230"
        #define TAG_RTCM_4072_0         "RTCM_4072_0"
        #define TAG_RTCM_4072_1         "RTCM_4072_1"
    #define TAG_MSGUBX "UBX"
        #define TAG_UBX_NAV_PVT         "UBX_NAV_PVT"
        #define TAG_UBX_NAV_RAWX        "UBX_NAV_RAWX"
        #define TAG_UBX_NAV_SFRBX       "UBX_NAV_SFRBX"
#define TAG_GNSS    "Use_Gnss"
    #define TAG_USE_GPS         "GPS"
    #define TAG_USE_SBAS        "SBAS"
    #define TAG_USE_GAL         "GAL"
    #define TAG_USE_BDS         "BDS"
    #define TAG_USE_IMES        "IMES"
    #define TAG_USE_QZSS        "QZSS"
    #define TAG_USE_GLO         "GLO"


u8* CreateDefaultCfg(void);
u8 ReadUbxConfig(void);

#endif //RECORDERCONFIGER_CONFIGUTIL_H
